package gui1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diba
 */
public class problem_solution extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form Adminlogin
     */
    public problem_solution(){
        initComponents();
        setResizable(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMango = new javax.swing.JButton();
        jPotato = new javax.swing.JButton();
        jRice = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jMango.setBackground(new java.awt.Color(0, 0, 0));
        jMango.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jMango.setForeground(new java.awt.Color(255, 255, 255));
        jMango.setText("Mango Tree");
        jMango.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jMango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMangoActionPerformed(evt);
            }
        });
        jPanel1.add(jMango);
        jMango.setBounds(340, 290, 180, 60);

        jPotato.setBackground(new java.awt.Color(0, 0, 0));
        jPotato.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jPotato.setForeground(new java.awt.Color(255, 255, 255));
        jPotato.setText("Potato");
        jPotato.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPotato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPotatoActionPerformed(evt);
            }
        });
        jPanel1.add(jPotato);
        jPotato.setBounds(340, 220, 180, 60);

        jRice.setBackground(new java.awt.Color(0, 0, 0));
        jRice.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jRice.setForeground(new java.awt.Color(255, 255, 255));
        jRice.setText("Rice");
        jRice.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRiceActionPerformed(evt);
            }
        });
        jPanel1.add(jRice);
        jRice.setBounds(340, 150, 180, 60);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Problem & Solution");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 10, 400, 70);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(763, 10, 80, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/problem_solution.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 850, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMangoActionPerformed
        // mango_page
        new mango_page().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jMangoActionPerformed

    private void jPotatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPotatoActionPerformed
        // potato
        new potato_page().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jPotatoActionPerformed

    private void jRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRiceActionPerformed
        // Rice
        new rice_page().setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jRiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agriculture_information obj =new agriculture_information();
        obj.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(problem_solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(problem_solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(problem_solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(problem_solution.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new problem_solution().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jMango;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPotato;
    private javax.swing.JButton jRice;
    // End of variables declaration//GEN-END:variables
}
